### ISSUE TITLE
I love the name of this org, can I join it?

### ISSUE THREAD

**Issue by ulysses4ever** [haskell-pkg-janitors/meta#1]
I'm ready to help with some janitor duties!

**Comment by andreasabel** [comment]
Welcome!
The idea is if you inherit a package (by a takeover) that should be preserved and maintained by and for the Haskell community, then you can place it here rather than in your personal account, so that fallback maintainers are available.

I think this organization needs some dusting and renewal, because after its foundation in the 2010s not a lot happened...

**Comment by ulysses4ever** [comment]
Sounds good, thank you!
